/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      customProps: {
        badges: ['new', 'green'],
        featured: true,
      },
    },
    {
      type: 'category',
      label: 'SDK',
      items: [
        'api/classes/SorosanSDK',
        'api/classes/ContractSDK',
        'api/classes/TokenSDK',
        'api/classes/UtilSDK',
      ],
    },
  ],

};

module.exports = sidebars;
